[package]
name = "ucan"
description = "Implement UCAN-based authorization with conciseness and ease!"
keywords = ["ucan", "authz", "jwt", "pki"]
categories = [
  "authorization",
  "cryptography",
  "encoding",
  "web-programming"
]
documentation = "https://docs.rs/ucan"
repository = "https://github.com/cdata/rs-ucan/"
homepage = "https://github.com/cdata/rs-ucan"
license = "Apache-2.0"
readme = "README.md"
version = "0.4.0-alpha.1"
edition = "2021"

[features]
default = []
web = []

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.52"
async-recursion = "1.0.0"
serde_json = "1.0.74"
serde = { version = "1.0.133", features = ["derive"] }
base64 = "0.13.0"
textnonce = "1.0.0"
log = "0.4.14"
url = "2.2.2"
bs58 = "0.4"

[dev-dependencies]
did-key = "0.1.1"
tokio = { version = "^1", features = ["macros", "rt"] }